# Generated by Django 3.2.4 on 2021-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
