# Generated by Django 3.2.4 on 2021-08-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210706_1352'),
        ('accounts', '0006_user_reset_salt'),
    ]

    operations = []
