# Generated by Django 3.2.4 on 2022-08-16 13:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0005_auto_20210706_1352_0006_user_reset_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
