include:
  - local: ".gitlab-tasks.yml"
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  tags:
    - docker

variables:
  STAGING_BRANCH: "feature/k8s-review-apps-test2"
  PROD_BRANCH: "master"
  SKIP_DEPLOY: "False"
  DOCKER_IMAGE: docker:20.10.14
  DEPLOY_IMAGE: alpine:latest
  DIND_SERVICE_IMAGE: docker:20.10.14-dind

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'

default:
  image: python:3.8

stages:
  - test
  - deploy
  - release

# STAGE: test
flake8:
  stage: test
  extends:
    - .pip-requirements
  script:
    - flake8
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    REQUIREMENTS_FILE: "requirements/test.txt"

Pytest:
  stage: test
  extends:
    - .pip-requirements
  services:
    - postgres:latest
  script:
    - pytest --cov-fail-under=$MIN_COVERAGE_BACKEND -c pytest-ci.ini
    - pwd
    - ls -la
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/backend/coverage.xml
    reports:
      junit: $CI_PROJECT_DIR/backend/report.xml
      cobertura:
        - $CI_PROJECT_DIR/backend/coverage.xml
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    POSTGRES_PASSWORD: unsafe
    REQUIREMENTS_FILE: "requirements/test.txt"
    MIN_COVERAGE_BACKEND: 70

Test Frontend:
  stage: test
  image: node:14
  before_script:
    - cd frontend && npm ci --cache .npm --prefer-offline
  script:
    - npm run test -- --coverageThreshold='{"global":{"statements":"$MIN_COVERAGE_FRONTEND"}}'
  tags:
    - docker
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - frontend/.npm/
  artifacts:
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/frontend/junit.xml
      cobertura: $CI_PROJECT_DIR/frontend/coverage/cobertura-coverage.xml
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    MIN_COVERAGE_FRONTEND: 15

# STAGE: build-staging
# Containerize Vue frontend and push to gitlab container registry
Build Frontend:
  stage: test
  environment:
    name: review/$CI_COMMIT_REF_NAME
  extends:
    - .docker-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENVIRONMENT: review
        NODE_ENV: review
        API_URL: https://forge-backend-$CI_MERGE_REQUEST_ID.k8s.liip.ch/api/v1/
        IMAGE_SUFFIX: staging
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH
      variables:
        ENVIRONMENT: staging
        NODE_ENV: staging
        API_URL: https://api.forge.bedev.liip.ch/api/v1/
        IMAGE_SUFFIX: staging
  variables:
    IMAGE_SUFFIX: $CI_COMMIT_SHORT_SHA
    APP: frontend
    DOCKERFILE: Dockerfile.frontend

# Containerize Vue frontend styleguide and push to gitlab container registry
Build Frontend Styleguide:
  stage: test
  extends:
    - .docker-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENVIRONMENT: review
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH
      variables:
        ENVIRONMENT: production
        IMAGE_SUFFIX: staging
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH
      variables:
        ENVIRONMENT: staging
        IMAGE_SUFFIX: staging
  variables:
    APP: frontend
    DOCKERFILE: Dockerfile.styleguide
    IMAGE_TAG: ${CI_REGISTRY}/${CI_PROJECT_PATH}:styleguide_${CI_COMMIT_SHORT_SHA}

# Containerize VuePress docs app and push to gitlab container registry
Build Forge Docs:
  stage: test
  extends:
    - .docker-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENVIRONMENT: review
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH
      variables:
        ENVIRONMENT: production
        IMAGE_SUFFIX: staging
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH
      variables:
        ENVIRONMENT: staging
        IMAGE_SUFFIX: staging
  variables:
    APP: docs

# STAGE: build-staging
# Containerize Django backend and push to gitlab container registry
Build Backend:
  stage: test
  extends:
    - .docker-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENVIRONMENT: review
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH
      variables:
        ENVIRONMENT: production
        IMAGE_SUFFIX: staging
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH
      variables:
        ENVIRONMENT: staging
        IMAGE_SUFFIX: staging
  variables:
    IMAGE_SUFFIX: $CI_COMMIT_SHORT_SHA
    APP: backend

# STAGE: deploy-staging
# Deploy merge request to k8s cluster.
Deploy Review App:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://forge-frontend-$CI_MERGE_REQUEST_ID.k8s.liip.ch
  extends:
    - .k8s-deploy
  rules:
    - if: ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH || $CI_COMMIT_TAG)
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    IMAGE_SUFFIX: $CI_COMMIT_SHORT_SHA
    ENVIRONMENT_NAMESPACE: forge-review
    FRONTEND_URL: forge-frontend-$CI_MERGE_REQUEST_ID.k8s.liip.ch
    BACKEND_URL: forge-backend-$CI_MERGE_REQUEST_ID.k8s.liip.ch

Stop Review App:
  stage: deploy
  extends:
    - .k8s-remove
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH || $CI_COMMIT_TAG)
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  variables:
    ENVIRONMENT_NAMESPACE: forge-review

# STAGE: deploy-staging
# Deployment on staging server
Deploy Staging:
  stage: deploy
  extends:
    - .docker-deploy
  environment:
    name: staging
    url: https://forge.bedev.liip.ch
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH
  variables:
    IMAGE_SUFFIX: staging
    DOMAIN: ${STAGING_DOMAIN}
    DEPLOYMENT_SSH_KEY: ${STAGING_SSH_PRIVATE_KEY}
    SSH_PORT: 22

# STAGE: release
# Create new gitlab release
Create Gitlab Release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH)
  needs:
    - job: Deploy Staging
      optional: true
  script:
    - echo "running release-job for $CI_COMMIT_SHORT_SHA"
  release:
    name: 'Release $CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    ref: '$CI_COMMIT_SHA'
  tags:
    - docker-privileged

# Create new sentry release and send sourcemaps
Update Sentry:
  stage: release
  image: getsentry/sentry-cli
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $STAGING_BRANCH || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $PROD_BRANCH) && $SENTRY_AUTH_TOKEN
  needs:
    - job: Deploy Staging
      optional: true
    - job: Build Frontend
      artifacts: true
      optional: true
  script:
    - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
    - export SENTRY_ORG=$SENTRY_ORG
    - export SENTRY_PROJECT=$SENTRY_PROJECT
    - echo "Creating new sentry release with tag $CI_COMMIT_SHORT_SHA..."
    - sentry-cli releases new $CI_COMMIT_SHORT_SHA
    - echo "Uploading sourcemaps files to Sentry..."
    - ls ${CI_PROJECT_DIR}/sourcemaps
    - sentry-cli releases files $CI_COMMIT_SHORT_SHA upload-sourcemaps ${CI_PROJECT_DIR}/sourcemaps
    - echo "Finalizing sentry release and setting commits..."
    - sentry-cli releases finalize $CI_COMMIT_SHORT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHORT_SHA
    - echo "Finalized release, set commits and uploaded sourcemaps for release $CI_COMMIT_SHORT_SHA"
  tags:
    - docker