version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./backend/.data/postgres_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - default
      - pontsun

  backend:
    build: ./backend
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    volumes:
      - ./backend/.venv:/venv
      - ./backend:/code
    environment:
      - INITIAL
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=http
      - traefik.http.routers.backend.rule=Host(`${BACKEND_URL}`)
      - traefik.http.services.backend.loadbalancer.server.port=8000
    networks:
      - default
      - pontsun
    ports:
      - 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    command: sh -c "npm install && npm run serve"
    volumes:
      - ./frontend:/code
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${FRONTEND_URL}`)
      - traefik.http.routers.frontend.entrypoints=http
      - traefik.http.services.frontend.loadbalancer.server.port=8080
    networks:
      - default
      - pontsun
    ports:
      - 8080

  styleguide:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    command: sh -c "npm install && npm run serve:styleguide"
    volumes:
      - ./frontend:/code
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.styleguide.rule=Host(`${STYLEGUIDE_URL}`)
      - traefik.http.routers.styleguide.entrypoints=http
      - traefik.http.services.styleguide.loadbalancer.server.port=6060
    networks:
      - default
      - pontsun
    ports:
      - 6060

  docs:
    build:
      context: ./docs
    command: sh -c "npm install && npm run start"
    volumes:
      - ./docs:/code
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.docs.rule=Host(`${DOCS_URL}`)
      - traefik.http.routers.docs.entrypoints=http
      - traefik.http.services.docs.loadbalancer.server.port=8081
    networks:
      - default
      - pontsun
    ports:
      - 8081

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./config/servers.pgadmin.json:/pgadmin4/servers.json
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_URL}`)
      - traefik.http.routers.pgadmin.entrypoints=http
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    networks:
      - default
      - pontsun
    ports:
      - 80

networks:
  default:
  pontsun:
    name: pontsun
