version: "3"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./backend/.data/postgres_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - default
      - pontsun

  backend:
    build: .
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    environment:
      INITIAL: "${INITIAL:-0}"
      DJANGO_ALLOWED_HOSTS: ${TRAEFIK_BACKEND_URL}
    volumes:
      - ./backend/.venv:/venv
      - ./backend:/code
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${TRAEFIK_BACKEND_URL}"
      - 'traefik.docker.network=pontsun'
    networks:
      - default
      - pontsun
    ports:
      - 8000

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run serve"
    volumes:
      - ./frontend:/code
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${TRAEFIK_FRONTEND_URL}'
      - 'traefik.docker.network=pontsun'
    networks:
      - default
      - pontsun
    ports:
      - 8080
  docs:
    build: ./docs
    command: sh -c "npm install && npm run start"
    volumes:
      - ./docs:/code
    stdin_open: true
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${TRAEFIK_DOCS_URL}'
      - 'traefik.docker.network=pontsun'
    networks:
      - default
      - pontsun
    ports:
      - 8080

  styleguide:
    build: ./frontend
    command: sh -c "npm install && npm run serve:styleguide"
    volumes:
      - ./frontend:/code
    stdin_open: true
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${TRAEFIK_STYLEGUIDE_URL}'
      - 'traefik.docker.network=pontsun'
    networks:
      - default
      - pontsun
    ports:
      - 6060

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./config/servers.pgadmin.json:/pgadmin4/servers.json
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${TRAEFIK_PGADMIN_URL}"
      - 'traefik.docker.network=pontsun'
    networks:
      - default
      - pontsun
    ports:
      - 80

networks:
  default:
  pontsun:
    external:
      name: pontsun
