backend:
  enabled: true

  image:
    repository: docker.gitlab.liip.ch/liip/forge
    pullPolicy: IfNotPresent
    tag: "backend_staging"

  configmap:
    # django environment
    data:
      FRONTEND_URL: john-frontend.k8s.liip.ch
      BACKEND_URL: john-api.k8s.liip.ch
      DEBUG: "true"
      SECRET_KEY: 'unsafesecretkey'
      ALLOWED_HOSTS: john-api.k8s.liip.ch
      CORS_ORIGIN_WHITELIST: https://john-frontend.k8s.liip.ch

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - host: john-api.k8s.liip.ch
    tls:
      - hosts:
          - john-api.k8s.liip.ch
        secretName: forge-backend-tls

frontend:
  enabled: true

  image:
    repository: docker.gitlab.liip.ch/liip/forge
    pullPolicy: Always
    tag: "frontend_staging"

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - host: john-frontend.k8s.liip.ch
    tls:
      - hosts:
          - john-frontend.k8s.liip.ch
        secretName: forge-frontend-tls