apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: forge-database
  labels:
    app: db
spec:
  type: ClusterIP
  externalName: db.forge-database.svc.cluster.local
  ports:
   - port: 5432
  selector:
    app: postgres