kind: Service
apiVersion: v1
metadata:
  name: counselor-frontend
  namespace: bag-counselor
spec:
  type: ClusterIP
  selector:
    app: counselor-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80