apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: forge-backend
spec:
  template:
    spec:
      containers:
        - name: django
          image: IMAGE
          imagePullPolicy: IfNotPresent
          command: ['python', 'manage.py', 'migrate']
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          envFrom:
          - configMapRef:
              name: env-file
      restartPolicy: Never
  backoffLimit: 5